### PR TITLE
Escape "query" parameter

### PR DESCRIPTION
**Pull request by thinca**
"query" parameter may contains any characters such as "&".

Sorry for no tests.
I'm newbie for Go.  Adding tests about them was difficult for me. :bow:

### CODE REVIEW

**Comment by sivchari** [comment]
Thank you for PR 😄, good catch !
Please update target branch `dev-1.1` to `main`. I wanna apply these changes for gotwtr immediately.

**Comment by thinca** [comment]
OK.  I rebased.
Note that `searchAllTweets` API does not not exist in `main`.  Therefore, you need to fix it in the `dev-1.1` branch.

**Comment by sivchari** [comment]
@thinca 

> Note that searchAllTweets API does not not exist in main. Therefore, you need to fix it in the dev-1.1 branch.

Yes, I know. I'll create PR for apply for your comment 👍

**Comment by thinca** [comment]
CI failed, but the test succeeds in my local environment.
It appears to be a cache issue in the CI environment.

**Comment by sivchari** [comment]
I used act (demonstrate github actions in local), and this CI is passed. So, I don't no idea that why is this checks is failed. You said cache issue in the CI environment, but we cached only go.sum. As these reason, the checks is failed, but I'd like to merge this PR. What do you think ?

**Comment by thinca** [comment]
Fmm...  Sorry, this is not the cache problem.

https://github.com/sivchari/gotwtr/pull/121/checks#step:2:205

> HEAD is now at 937d90b Merge b9c61bf850d787898b0b24b2281b20ce5ed35f31 into 749a04a3b31705ffa56573d22042bb6b2c280ea3

749a04a3b31705ffa56573d22042bb6b2c280ea3 is a commit at `dev-1.1`.  The CI is not updating the merge point.

I'll try update it by close/reopen this PR.

**Comment by thinca** [comment]
Oh... re-approval is needed.

**Comment by sivchari** [comment]
Hi, I comprehended, so I approve now.

**Pull request merged**
